title: "Robert's AI Insights"
description: "Weekly AI industry updates and digital transformation insights"
url: "https://blog.imetrobert.com"
baseurl: ""
author: "Robert Simon"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Social links (matching your main site)
social:
  twitter: robertsimon
  linkedin: imetrobert

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/