/**
 * Creates the "Canadian AI Pulse" form.
 *
 * Generated by scripts/make_form_script.py from data/survey.json — do not
 * hand-edit the wording here. If a question changes, change it in
 * data/survey.json and regenerate, or the counts you submit later will be
 * rejected for not matching the configured options.
 *
 * HOW TO RUN
 *   1. Go to script.google.com and start a new project
 *   2. Replace everything in the editor with this file
 *   3. Click Run, and approve the permission prompt
 *   4. Open View > Logs — it prints the form URL
 *   5. Put that URL in form_url in data/survey.json
 */
function createSurveyForm() {
  var form = FormApp.create("Canadian AI Pulse");
  form.setDescription("Five questions, under a minute. Results are published openly with the sample size, so you can compare your position against the rest of the readership. No email required.");
  form.setCollectEmail(false);
  form.setProgressBar(true);
  form.setConfirmationMessage('Thank you — results are published on imetrobert.com/blog/canadian-ai-pulse.html');

  form.addMultipleChoiceItem()
    .setTitle("Where is your organization with AI today?")
    .setChoiceValues(["Not started", "Experimenting informally", "Running pilots", "In production in one area", "In production across multiple areas"])
    .setRequired(true);

  form.addMultipleChoiceItem()
    .setTitle("What is the single biggest thing blocking you?")
    .setChoiceValues(["Budget", "Skills and hiring", "Data readiness", "Governance and compliance", "Leadership buy-in", "Nothing significant"])
    .setRequired(true);

  form.addMultipleChoiceItem()
    .setTitle("How has your AI spend changed in the last six months?")
    .setChoiceValues(["Increased significantly", "Increased slightly", "Stayed flat", "Decreased"])
    .setRequired(true);

  form.addMultipleChoiceItem()
    .setTitle("Does your organization have a written AI usage policy?")
    .setChoiceValues(["Yes, and it is enforced", "Yes, but informally applied", "In progress", "No"])
    .setRequired(true);

  form.addMultipleChoiceItem()
    .setTitle("How many employees does your organization have?")
    .setChoiceValues(["Under 50", "50 to 249", "250 to 999", "1,000 or more"])
    .setRequired(false);

  // Optional free text. Not tallied on the site — it is there to tell you
  // what to write about next.
  form.addParagraphTextItem()
    .setTitle('What is the one AI question you want answered next month?')
    .setRequired(false);

  Logger.log('Public form URL (put this in form_url): ' + form.getPublishedUrl());
  Logger.log('Edit URL (keep private): ' + form.getEditUrl());
}
