"""
make_form_script.py
Generates a Google Apps Script that builds the survey form in one click.

Creating the form is the one part of the survey loop that cannot be done from
this repo — it needs a Google account. Typing five questions and twenty-three
options into the Forms UI by hand is both tedious and the easiest place to
introduce a typo, and a typo matters here: add_survey_wave.py validates the
counts you later submit against the option text in data/survey.json, so an
option worded differently in the form than in the config is rejected at
publish time, months after the mistake was made.

So the script is generated FROM data/survey.json. The form and the validator
come from the same source and cannot disagree.

    python3 scripts/make_form_script.py > survey-form.gs

Then: script.google.com -> New project -> paste -> Run. It prints the form's
public URL, which goes in the form_url field of data/survey.json.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG = os.path.join(ROOT, "data", "survey.json")


def js(s):
    return json.dumps(s, ensure_ascii=False)


def build():
    with open(CONFIG, encoding="utf-8") as f:
        cfg = json.load(f)

    questions = cfg.get("questions", [])
    lines = [
        "/**",
        f" * Creates the \"{cfg.get('survey_name', 'survey')}\" form.",
        " *",
        " * Generated by scripts/make_form_script.py from data/survey.json — do not",
        " * hand-edit the wording here. If a question changes, change it in",
        " * data/survey.json and regenerate, or the counts you submit later will be",
        " * rejected for not matching the configured options.",
        " *",
        " * HOW TO RUN",
        " *   1. Go to script.google.com and start a new project",
        " *   2. Replace everything in the editor with this file",
        " *   3. Click Run, and approve the permission prompt",
        " *   4. Open View > Logs — it prints the form URL",
        " *   5. Put that URL in form_url in data/survey.json",
        " */",
        "function createSurveyForm() {",
        f"  var form = FormApp.create({js(cfg.get('survey_name', 'Survey'))});",
        f"  form.setDescription({js('Five questions, under a minute. Results are published openly with the sample size, so you can compare your position against the rest of the readership. No email required.')});",
        "  form.setCollectEmail(false);",
        "  form.setProgressBar(true);",
        "  form.setConfirmationMessage('Thank you — results are published on imetrobert.com/blog/canadian-ai-pulse.html');",
        "",
    ]

    for q in questions:
        lines.append(f"  form.addMultipleChoiceItem()")
        lines.append(f"    .setTitle({js(q['text'])})")
        lines.append(f"    .setChoiceValues([{', '.join(js(o) for o in q['options'])}])")
        lines.append(f"    .setRequired({'false' if q.get('segmentation') else 'true'});")
        lines.append("")

    lines += [
        "  // Optional free text. Not tallied on the site — it is there to tell you",
        "  // what to write about next.",
        "  form.addParagraphTextItem()",
        "    .setTitle('What is the one AI question you want answered next month?')",
        "    .setRequired(false);",
        "",
        "  Logger.log('Public form URL (put this in form_url): ' + form.getPublishedUrl());",
        "  Logger.log('Edit URL (keep private): ' + form.getEditUrl());",
        "}",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = build()
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w", encoding="utf-8") as f:
            f.write(out)
        print(f"Wrote {sys.argv[1]}")
    else:
        sys.stdout.write(out)
